gText_Carter_Welcome::
	.string "Hey dude! Welcome to your\n"
	.string "very own version of\l"
	.string "POKéMON Emerald!\p"
	.string "This is BEN, but here everyone\n"
	.string "just calls me the POKéMON\l"
	.string "PROFESSOR.\p"
	.string "$"

gText_Carter_Pokemon::
	.string “Let me show you one of my POKéMON!\p”
	.string “\n”
	.string “$”

gText_Carter_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Carter_AndYouAre::
	.string "And you're BRALEN, right?$"

gText_Carter_NotBralen::
	.string "Come on dude, quit\n"
	.string "fucking with me!\l"
	.string "You're BRALEN, right?$"

gText_Carter_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Carter_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Carter_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Carter_YourePlayer::
	.string "Hell yeah {PLAYER}, allow me\n"
	.string "to welcome you to the lovely\l"
	.string "town of LITTLEROOT.\p"
	.string "$"

gText_Carter_AreYouReady::
	.string "Are you ready?\p"
	.string "Your adventure is about to unfold.\p"
	.string "Have fun as you leap back into\n"
	.string "the world of POKéMON that we\l"
	.string "cherished as kids!\p"
	.string "I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
