gText_Carter_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is CARTER.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Carter_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Carter_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Carter_AndYouAre::
	.string "And you're BRALEN, right?$"

gText_Carter_NotBralen::
	.string "Come on dude, quit\n"
	.string "fucking with me!\l"
	.string "You're BRALEN, right?$"

gText_Carter_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Carter_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Carter_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Carter_YourePlayer::
	.string "Hell yeah, so you're\n"
	.string "{PLAYER}{KUN} who's moving to my\l"
	.string "hometown of LITTLEROOT.\p"
	.string "$"

gText_Carter_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
